---
title: "hw2-XuBin-Kuang"
author: "Xu-Bin Kuang"
date: "01/10/2017"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
setwd("/Users/KuangXu-Bin/Desktop/Berkeley/Fall_2017/stat133/stat133-hws-fall17/hw02")
```

```{r}
DataBase <- data.frame(read.csv(csv, header = TRUE, colClasses=c("Player"="character", "Team" = "character", "Experience" = "character", "Position" = "factor", "Salary" = 'double')))
str(DataBase)
```

```{r}
library(readr)
DataReadr <- read_csv(csv, col_types = cols(.default = col_integer(),Player = col_character(), Team = col_character(), Position = col_factor(c('C','PF','PG','SF','SG')), Experience = col_character(), Salary = col_double()))
str(DataReadr)

```

```{r}
DataBase$Experience <- replace(as.character(DataBase$Experience), DataBase$Experience == "R", 0)
DataBase$Experience = as.integer(DataBase$Experience)
```

```{r}
DataBase$Missed_FG = DataBase$FGA - DataBase$FGM
DataBase$Missed_FT = DataBase$FTA - DataBase$FTM
DataBase$PTS = 2 * DataBase$Points2 + 3 * DataBase$Points3 + DataBase$FTM
DataBase$REB = DataBase$OREB + DataBase$DREB
DataBase$MPG = DataBase$MIN/DataBase$GP
```

```{r}
DataBase$EFF = (DataBase$PTS + DataBase$REB + DataBase$AST + DataBase$STL + DataBase$BLK - DataBase$Missed_FG - DataBase$Missed_FT - DataBase$TO) / DataBase$GP

summary(DataBase$EFF)
```

```{r}
hist(DataBase$EFF, xlab = "EFF", main = "Histogram of Efficient(EFF)", col = "gray")
```

```{r}
#Top 10 EFF
library(dplyr)
Top = arrange(DataBase, desc(EFF))
Top = slice(Top, 1:10)
Top = select(Top, Player, Team, Salary, EFF)
```


```{r}
#Players with Negative EFF
DataBase$Player[DataBase$EFF < 0]
```

```{r}
#Computed Correlations
corr_coff <- c(cor(DataBase$EFF, DataBase$PTS), cor(DataBase$EFF, DataBase$REB), cor(DataBase$EFF, DataBase$AST), cor(DataBase$EFF, DataBase$STL), cor(DataBase$EFF, DataBase$BLK), cor(DataBase$EFF, -DataBase$Missed_FG), cor(DataBase$EFF, -DataBase$Missed_FT), cor(DataBase$EFF, -DataBase$TO))

barplot(corr_coff, main = "Correlations between Player Stats and EFF", names.arg = c("PTS", "REB", "STL", "AST", "BLK", "Missed_FT", "Missed_FG", "TO"), ylim=c(-1,1), col = c("gray", "gray", "gray", "gray", "gray", "red", "red", "red") )
abline( h = 0)
```

```{r}
#Efficiency and Salary
plot(DataBase$EFF, DataBase$Salary, main = "Plot of Efficiency and Salary", xlab = "Efficiency", ylab = "Salary")
lines(lowess(DataBase$EFF, DataBase$Salary, f = 2/3, iter = 3))
corr = cor(DataBase$EFF, DataBase$Salary)
corr
#Since corr is > 0, there's a positive correlation between Efficiency and Salary. The lowess line is less steep in the beginning, indicating that at lower levels of efficiency, slight increases in efficicenty corresponds with a low change in salary. However, above an EFF score of 15, the change looks to be proportional as shown by the steep lowess line. This could be because this me
```

```{r}
players2 <- data.frame(subset(DataBase, DataBase$MPG >= 20))
plot(players2$EFF, players2$Salary, main = "Plot of Efficiency and Salary", xlab = "Efficiency", ylab = "Salary")
lines(lowess(players2$EFF, players2$Salary, f = 2/3, iter = 3))
corr = cor(players2$EFF, players2$Salary)
corr

#The correlation is lower for more established players because there is a better track record for teams to decide on after rookies have been removed. 
```