---
title: "lab5-XuBin-Kuang"
author: "Xu-Bin Kuang"
date: "03/10/2017"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(dplyr)
library(ggplot2)
```

```{r}
dat <- read.csv('nba2017-players.csv', stringsAsFactors = FALSE)
```

```{r}
five_rows <- slice(dat, 1:5)
fifth_slice <- slice(dat, c(10,15,20,25,30,35,40,45,50))
last <- tail(dat,5)
last_slice <- slice(last, 1:5)
filter(dat, height < 70)
gsw <- filter(dat, team == 'GSW')
filter(dat, team == 'GSW' && position == 'C')
select(filter(dat,team == 'LAL'), player)
select(filter(dat,team == 'GSW', position == 'PG'), player, salary)
select(filter(dat, experience > 10, salary < 10000000), player, age, team)
select(filter(dat, experience > 10, salary < 10000000), player, age, team)
select(slice(filter(dat, experience == 0, age == 20), 1:5), player, team, weight, height)
```

```{r}
mutate(gsw, ht_wt = height * weight)
gsw3 <- mutate(gsw , log_height = log(height), log_weight = log(weight))
arrange(filter(dat, height < 71), height)
select(head(arrange(dat,desc(salary)), 5), player, team, salary)
select(head(arrange(dat, desc(points3)), 10), player, team, points3)
gsw_mpg <- mutate(gsw, min_per_game = minutes/games)
gsw_mpg <- arrange(select(gsw_mpg, player, experience, min_per_game), desc(min_per_game))

```

```{r}
summarise(dat, max_height = max(height))
summarise(group_by(dat, team), med_points3 = median(points3))
summarise(group_by(dat, team), aver_points3 = mean(points3))
arrange(summarise(group_by(dat, team), aver_points3 = mean(points3)), aver_points3)
summarise(filter(dat, position == 'PF', experience < 10, experience > 5), std_age = sd(age), ave_age = mean(age))

```
obtain the mean and standard deviation of age, for Power Forwards, with 5 and 10 years (including) years of experience.
```{r}
ggplot(gsw, aes(x = height, y = weight)) + geom_point()
ggplot(gsw, aes(x = height, y = weight)) + geom_point() + geom_text(aes(label = player),hjust=0, vjust=0)
ggplot(gsw, aes(x = height, y = weight)) + geom_point() + geom_label(aes(label = player),hjust=0, vjust=0)
ggplot(gsw, aes(x = salary)) + geom_density()
ggplot(gsw, aes(x = points2)) + geom_histogram(binwidth = 50)
ggplot(gsw, aes(x = position)) + geom_bar()
ggplot(filter(gsw, position == 'C'), aes(x = experience, y = salary)) + geom_point() + geom_label(aes(label = player),hjust=0, vjust=0) + geom_smooth(method = lm)
ggplot(filter(dat, position == 'C'), aes(x = experience, y = salary)) + geom_point() + geom_label(aes(label = player),hjust=0, vjust=0) + geom_smooth()
```

```{r}
ggplot(data = dat, aes(x = experience, y = salary)) +
  geom_point() +
  facet_wrap(~ position)
ggplot(data = dat, aes(x = experience, y = salary)) +
  geom_point() +
  facet_wrap(~ team)
ggplot(data = dat, aes(x = age)) + geom_density() + facet_wrap(~ team)
ggplot(data = dat, aes(x = height, y = weight)) +
  geom_point() +
  facet_wrap(~ position)
ggplot(data = dat, aes(x = height, y = weight)) +
  geom_density_2d() +
  facet_wrap(~ position)
```

```{r}
ggplot(data = gsw, aes(x = experience, y = salary)) +geom_point() + theme_bw()
ggplot(data = dat, aes(x = height, y = weight)) + geom_density_2d() + facet_wrap(~ position) + theme_minimal()
ggplot(data = dat, aes(x = experience, y = salary)) + geom_point() + facet_wrap(~ team) + theme_dark()
ggplot(filter(dat, position == 'C'), aes(x = experience, y = salary)) + geom_point() + geom_label(aes(label = player),hjust=0, vjust=0) + geom_smooth() + theme_classic()



```








